// import './example/basic_type'
// import './example/symbol'
// import './example/interface'
// import './example/func'
// import './example/generics'
// import './example/ex6-class'
// import './example/class'
// import './example/enum'
// import './example/interface-compat'
// import './example/advance-type1'
// import './example/advance-type2'
// import './module/index.js'
// import './ts-module/index'
// import './example/merging'
import './example/decorate'
